[package]
name = "neovim-http-client"
version = "0.1.0"
authors = ["daavidjobe <daavid.jobe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = "0.6.1"
